### ISSUE TITLE
Additional instructions

### ISSUE THREAD

**Issue by DavidAustinNix** [nickGermi/aws-force-mfa#1]
Thanks Nick, this is tremendously helpful.  A couple suggestions to help others get up and going here.

1) Add the provided IAM policy to the UserGroup or User _in addition_ to their existing IAM policy.  Both are needed.

2) Add a reminder that one must source the bash authenticator to get the env vars out of the sub shell:
echo "Be sure you are using 'source' to execute this MFA AWS authentication script (e.g. source ~/Aws/authenticate.sh)"

**Comment by nickGermi** [comment]
> Add the provided IAM policy to the UserGroup or User in addition to their existing IAM policy. Both are needed.

Covered [here](https://github.com/nickGermi/aws-force-mfa#instructions-to-enforce-mfa-for-iam-users-for-admins), you may of course use `IAM user group`s to make life easier for yourself but that would be outside of the scope of this repository.

> Be sure you are using 'source' to execute

An example is already provided under "authenticate.sh for OSX"
